// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext( typeof( ApplicationContext ) )]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel( ModelBuilder modelBuilder )
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation( "ProductVersion", "6.0.8" )
                .HasAnnotation( "Relational:MaxIdentifierLength", 128 );

            SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );

            modelBuilder.Entity( "DAL.Models.ToDoList", b =>
                {
                    b.Property<int>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "int" );

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

                    b.Property<DateTime>( "DateOfCreation" )
                        .HasColumnType( "datetime2" );

                    b.Property<DateTime>( "DeadlineDate" )
                        .HasColumnType( "datetime2" );

                    b.Property<string>( "Description" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<bool>( "IsDeleted" )
                        .HasColumnType( "bit" );

                    b.Property<int>( "Status" )
                        .HasColumnType( "int" );

                    b.Property<string>( "Title" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.HasKey( "Id" );

                    b.ToTable( "ToDoLists" );
                } );
#pragma warning restore 612, 618
        }
    }
}
